<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.7.12">
]
>

<object class="java.util.Vector" name="__root__" version="3.7.12">
   <object class="weka.classifiers.bayes.NaiveBayes" name="0">
      <object array="yes" class="java.lang.String" name="options"/>
   </object>
   <object class="weka.classifiers.functions.Logistic" name="1">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-R</object>
         <object class="java.lang.String" name="1">1.0E-8</object>
         <object class="java.lang.String" name="2">-M</object>
         <object class="java.lang.String" name="3">-1</object>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="2">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-S</object>
         <object class="java.lang.String" name="1">-C</object>
         <object class="java.lang.String" name="2">0.25</object>
         <object class="java.lang.String" name="3">-B</object>
         <object class="java.lang.String" name="4">-M</object>
         <object class="java.lang.String" name="5">2</object>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="3">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-S</object>
         <object class="java.lang.String" name="1">-C</object>
         <object class="java.lang.String" name="2">0.25</object>
         <object class="java.lang.String" name="3">-B</object>
         <object class="java.lang.String" name="4">-M</object>
         <object class="java.lang.String" name="5">2</object>
         <object class="java.lang.String" name="6">-A</object>
      </object>
   </object>
   <object class="weka.classifiers.trees.J48" name="4">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-S</object>
         <object class="java.lang.String" name="1">-C</object>
         <object class="java.lang.String" name="2">0.25</object>
         <object class="java.lang.String" name="3">-M</object>
         <object class="java.lang.String" name="4">2</object>
      </object>
   </object>
</object>
